version: "3.8"
services:
  blue:
    image: ttasjwi/board-be:latest
    container_name: green
    ports:
      - "8082:8080"
    volumes:
      - "./keys:/app/keys"
    environment:
      - SERVER_PROFILE=green
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
      - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
      - GOOGLE_OAUTH2_REDIRECT_URI=${GOOGLE_OAUTH2_REDIRECT_URI}
      - GOOGLE_OAUTH2_SCOPE=${GOOGLE_OAUTH2_SCOPE}
      - NAVER_OAUTH2_CLIENT_ID=${NAVER_OAUTH2_CLIENT_ID}
      - NAVER_OAUTH2_CLIENT_SECRET=${NAVER_OAUTH2_CLIENT_SECRET}
      - NAVER_OAUTH2_AUTHORIZATION_GRANT_TYPE=${NAVER_OAUTH2_AUTHORIZATION_GRANT_TYPE}
      - NAVER_OAUTH2_REDIRECT_URI=${NAVER_OAUTH2_REDIRECT_URI}
      - NAVER_OAUTH2_SCOPE=${NAVER_OAUTH2_SCOPE}
      - KAKAO_OAUTH2_CLIENT_ID=${KAKAO_OAUTH2_CLIENT_ID}
      - KAKAO_OAUTH2_CLIENT_SECRET=${KAKAO_OAUTH2_CLIENT_SECRET}
      - KAKAO_OAUTH2_REDIRECT_URI=${KAKAO_OAUTH2_REDIRECT_URI}
      - KAKAO_OAUTH2_SCOPE=${KAKAO_OAUTH2_SCOPE}
      - RSA_ACCESS_TOKEN_PUBLIC_KEY_PATH=file:/app/keys/access-token_public-key.pem
      - RSA_ACCESS_TOKEN_PRIVATE_KEY_PATH=file:/app/keys/access-token_private-key.pem
      - RSA_REFRESH_TOKEN_PUBLIC_KEY_PATH=file:/app/keys/refresh-token_public-key.pem
      - RSA_REFRESH_TOKEN_PRIVATE_KEY_PATH=file:/app/keys/refresh-token_private-key.pem
