spring.application.name: board-system
spring:
  profiles:
    active: local
    group:
      local: local, localSecret
      blue: blue, production, productionSecret
      green: green, production, productionSecret
  config:
    import:
      - db-config.yml
      - security-config.yml
      - email-send-config.yml
      - deploy-config.yml
      - message-config.yml
