server:
  port: 8080
spring:
  profiles:
    active: ${SERVER_PROFILE:local}
  application:
    name: board-system
  config:
    import:
      - database.yml
      - redis.yml
      - email-sender.yml
      - optional:email-sender-secret.yml
      - web-support.yml
      - oauth2-client.yml
      - jwt.yml
      - optional:oauth2-client-secret.yml
