spring:
  config:
    activate:
      on-profile: localSecret
    import:
      - email-send-config-localSecret.yml

---

spring:
  config:
    activate:
      on-profile: productionSecret
    import:
      - file:/app/config/board-system/email-send-config-productionSecret.yml

---
