spring:
  config:
    activate:
      on-profile: local
    import: deploy-config-local.yml

---

spring:
  config:
    activate:
      on-profile: blue
    import: file:/app/config/board-system/deploy-config-blue.yml

---

spring:
  config:
    activate:
      on-profile: green
    import: file:/app/config/board-system/deploy-config-green.yml

---
