spring:
  config:
    activate:
      on-profile: local

rsa-keypair:
  public-key-path: classpath:/rsa-keypair/public_key_local.pem
  private-key-path: classpath:/rsa-keypair/private_key_local.pem

---

spring:
  config:
    activate:
      on-profile: localSecret
    import: security-config-localSecret.yml

---

spring:
  config:
    activate:
      on-profile: test

rsa-keypair:
  public-key-path: classpath:/rsa-keypair/public_key_test.pem
  private-key-path: classpath:/rsa-keypair/private_key_test.pem

---

spring:
  config:
    activate:
      on-profile: productionSecret
    import: file:/app/config/board-system/security-config-productionSecret.yml

rsa-keypair:
  public-key-path: file:/app/config/board-system/public_key_productionSecret.pem
  private-key-path: file:/app/config/board-system/private_key_productionSecret.pem

---
