name: Build-Test

on:
  pull_request:
    branches:
      - master

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    env:
      SERVER_PROFILE: test
      DATABASE_URL: jdbc:mysql://127.0.0.1:3306/board_db_test
      DATABASE_NAME: board_db_test
      DATABASE_ROOT_PASSWORD: root
      DATABASE_USERNAME: board_user_test
      DATABASE_PASSWORD: db1004
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
      GOOGLE_OAUTH2_REDIRECT_URI: ${{ secrets.GOOGLE_OAUTH2_REDIRECT_URI }}
      GOOGLE_OAUTH2_SCOPE: ${{ secrets.GOOGLE_OAUTH2_SCOPE }}
      NAVER_OAUTH2_CLIENT_ID: ${{ secrets.NAVER_OAUTH2_CLIENT_ID }}
      NAVER_OAUTH2_CLIENT_SECRET: ${{ secrets.NAVER_OAUTH2_CLIENT_SECRET }}
      NAVER_OAUTH2_AUTHORIZATION_GRANT_TYPE: ${{ secrets.NAVER_OAUTH2_AUTHORIZATION_GRANT_TYPE }}
      NAVER_OAUTH2_REDIRECT_URI: ${{ secrets.NAVER_OAUTH2_REDIRECT_URI }}
      NAVER_OAUTH2_SCOPE: ${{ secrets.NAVER_OAUTH2_SCOPE }}
      KAKAO_OAUTH2_CLIENT_ID: ${{ secrets.KAKAO_OAUTH2_CLIENT_ID }}
      KAKAO_OAUTH2_CLIENT_SECRET: ${{ secrets.KAKAO_OAUTH2_CLIENT_SECRET }}
      KAKAO_OAUTH2_REDIRECT_URI: ${{ secrets.KAKAO_OAUTH2_REDIRECT_URI }}
      KAKAO_OAUTH2_SCOPE: ${{ secrets.KAKAO_OAUTH2_SCOPE }}

    steps:
      - name: Check Out (체크 아웃)
        uses: actions/checkout@v4

      - name: 데이터베이스 설정
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE ${{ env.DATABASE_NAME }};" -uroot -p${{ env.DATABASE_ROOT_PASSWORD }}
          mysql -e "CREATE user '${{ env.DATABASE_USERNAME }}'@'%' IDENTIFIED BY '${{ env.DATABASE_PASSWORD }}';" -uroot -p${{ env.DATABASE_ROOT_PASSWORD }}
          mysql -e "GRANT ALL ON *.* TO '${{ env.DATABASE_USERNAME }}'@'%';" -uroot -p${{ env.DATABASE_ROOT_PASSWORD }}
          mysql -e "FLUSH PRIVILEGES;" -uroot -p${{ env.DATABASE_ROOT_PASSWORD }}

      - name: Redis 설정
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 7.4.1

      - name: Setup Java Version (Java 21 설정)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Use Gradle Cache (Gradle 캐싱)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew (gradlew에 권한 부여)
        run: chmod +x gradlew
        shell: bash

      - name: Test (테스트)
        run: ./gradlew build
